sp:
  user-service:
    users: "[{\"id\":1, \"username\":\"abc\",\"password\":\"123\"},{\"id\":2, \"username\":\"def\",\"password\":\"456\"},{\"id\":3, \"username\":\"ghi\",\"password\":\"789\"},{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":66, \"username\":\"vvv\",\"password\":\"987\"}]"

spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.64.5
    port: 5672
    username: admin
    password: admin  
    
server:
  port: 8101

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
#新的配置,暴露端点,动态处理远程仓库配置,项目动态获取数据
management:
  endpoints:
    web:
      exposure:
        include: refresh